const truthQuestions=[
  'What harmless habit would your closest friend tease you about?',
  'What tiny thing instantly improves your mood?',
  'Which movie character is secretly most like you?',
  'What is the sweetest compliment you still remember?',
  'What would your perfect slow Sunday together include?',
  'Which song would belong on the soundtrack of our first road trip?',
  'What is one romantic gesture that feels meaningful rather than expensive?',
  'What food could always convince you to stay for one more hour?',
  'What is your funniest first-date fear?',
  'When do you feel most confident and completely yourself?',
  'What childhood dream still makes you smile?',
  'Which small daily ritual would you love to share with a partner?',
  'What quality makes someone feel emotionally safe to you?',
  'What is one green flag you notice immediately?',
  'What would your ideal surprise date look like?',
  'Which family tradition would you want to keep in your future home?',
  'What is a silly opinion you will defend forever?',
  'What makes a conversation unforgettable for you?',
  'Which place would you love to revisit with someone special?',
  'What is one thing you are proud of but rarely mention?',
  'How do you usually show someone that you care?',
  'What kind of message makes you smile at your phone?',
  'Which ordinary moment can feel romantic with the right person?',
  'What is your most lovable imperfection?',
  'What would make you feel supported during a difficult week?',
  'Which dream feels more exciting when you imagine sharing it?',
  'What is the funniest misunderstanding you have ever had?',
  'What does a peaceful home feel like to you?',
  'What is something new you would be excited to learn together?',
  'When you care about someone, what do you notice first?',
  'What is your favorite way to celebrate a small win?',
  'Which memory always makes you laugh no matter how many times you tell it?',
  'What does loyalty look like in everyday life?',
  'What is one question you wish people asked you more often?',
  'Which season feels most romantic to you and why?',
  'What is your dream two-hour date when there is no time for a full day?',
  'What kind of affection makes you feel most understood?',
  'Which part of your personality takes time for people to discover?',
  'What is one future milestone you would want to celebrate quietly?',
  'What makes you feel listened to during a disagreement?',
  'Which smell instantly brings back a happy memory?',
  'What would your dream breakfast-for-two include?',
  'What is one spontaneous thing you would genuinely enjoy doing together?',
  'Which value would you want your future home to be known for?',
  'What is the kindest thing someone has done for you unexpectedly?',
  'What playful nickname would fit your personality?',
  'What would make meeting each other’s friends feel comfortable?',
  'Which simple promise matters more to you than a grand gesture?',
  'What does being a real team mean to you?',
  'If tonight became a perfect memory, what would happen next?',
] as const;

const dareChallenges=[
  'Send a dramatic 10-second voice note describing your perfect chai.',
  'Describe our imaginary first road trip using only five emojis.',
  'Give me a funny nickname and explain its origin story.',
  'Write a two-line movie trailer for our first date.',
  'Choose one song and dedicate its mood—not its lyrics—to this chat.',
  'Invent a dessert named after our combined personalities.',
  'Send the most wholesome pickup line you can create in 20 seconds.',
  'Plan a date using only three words and three emojis.',
  'Describe your current mood like a weather forecast.',
  'Do your best imaginary award speech for “Best Conversation Partner.”',
  'Share a photo of one ordinary object and make it sound romantic.',
  'Create a secret handshake using three emoji instructions.',
  'Write a one-sentence postcard from our imaginary weekend away.',
  'Pick our fictional couple mascot and defend your choice.',
  'Send a voice note saying “coffee?” in your most dramatic movie voice.',
  'Create a tiny menu for a dinner you would cook together.',
  'Describe your perfect hug without using the word hug.',
  'Give this conversation a playful episode title.',
  'Choose a color for today’s vibe and explain it in one sentence.',
  'Invent one adorable house rule for a future shared home.',
  'Send three emojis that describe your ideal Saturday and let me guess.',
  'Write a six-word love story about two people who missed the same train.',
  'Make up a funny headline about how we became travel legends.',
  'Choose a snack for me based only on this conversation.',
  'Describe a surprise date as if it were a mystery clue.',
  'Send your best “I have a brilliant plan” expression as an emoji combo.',
  'Create a harmless dare for me that can be completed in this chat.',
  'Write one sentence that would make a rainy day feel cozy.',
  'Give me a three-option mini poll for our imaginary next date.',
  'Turn your favorite comfort food into a superhero name.',
  'Write a sweet good-morning message for a day that starts too early.',
  'Choose one place nearby and pitch it as the world’s most romantic spot.',
  'Send a five-second laugh or smile voice note—no words needed.',
  'Invent a code word that means “I need encouragement today.”',
  'Create a tiny bucket list with one easy, one funny, and one brave idea.',
  'Describe a perfect sunset date without mentioning the sky.',
  'Send an emoji riddle about something you genuinely enjoy.',
  'Write the opening line of a cozy story starring both of us.',
  'Choose a flower that matches your personality and explain why.',
  'Create a funny review of our imaginary first cooking attempt.',
  'Send one sincere compliment and one obviously silly compliment.',
  'Invent a dance move name for celebrating good news together.',
  'Build a three-song mood playlist using song titles only.',
  'Write a tiny invitation to an at-home date night.',
  'Give me a travel challenge that costs less than ten dollars.',
  'Describe our imaginary café using its name, signature drink, and one rule.',
  'Create a two-emoji signal for “thinking of you.”',
  'Send a voice note describing your dream weekend in exactly ten words.',
  'Write one promise for keeping future disagreements respectful.',
  'Finish this sentence creatively: “The best part of getting to know you is…”',
] as const;

export const truthOrDarePrompts=Array.from({length:100},(_,index)=>{
  const promptIndex=Math.floor(index/2);
  return index%2===0?`TRUTH · ${truthQuestions[promptIndex]}`:`DARE · ${dareChallenges[promptIndex]}`;
});

export const truthOrDarePromptCount=truthOrDarePrompts.length;
